# Generated by Django 5.2.7 on 2025-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
    ]
