# Generated by Django 5.2.7 on 2025-11-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'permissions': [('can_promote_student', 'Can promote student'), ('can_expel_student', 'Can expel student')], 'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
    ]
